### ISSUE TITLE
matlab kernel send 2 display_data messages for one plotly visualization

### ISSUE THREAD

**Issue by Ga2nibal** [imatlab/imatlab#26] opened 2017-09-08 14:06 UTC
I try to run next code:

imatlab_export_fig('fig2plotly');
x = linspace(-10,10,100);
y = x;
[X,Y] = ndgrid(x,y);
surf(x,y,sin(X+Y))

and see imatlab kernel send 2 display_data messages.
1st. message looks like plotly definition (script type='text/javascript'>if(!window.Plotly){define(....))
2d. plotly js with visualization data

Can i configure imatlab kernel to turn off sending 1st display_data message(plotly define) sending for each vizualization?

**Comment by anntzer** [comment] 2017-09-08 19:35
I cannot reproduce the issue with Py 3.6 / MATLAB 2016b / notebook 5.0 (with NotebookApp.iopub_data_rate_limit set appropriately, see https://github.com/imatlab/imatlab/issues/2#issuecomment-294107129) / imatlab 0.2.
![screenshot_20170908_123248](https://user-images.githubusercontent.com/1322974/30228356-2504fb0c-9492-11e7-9265-397747596440.png)

Please clarify the issue.

**Comment by Ga2nibal** [comment] 2017-09-09 11:54
i saw the same picture. but when i looked on messages from imatlab kernel. i saw 2 'display_data' messages. and i think that first message  is optional. The frontend can display visualization without him.
And my question, are there approach to disable sending this message from kernel?

![imatlab-jupyter-messages](https://user-images.githubusercontent.com/10108300/30239911-97ceab56-956e-11e7-86d2-6198f7c19903.png)

**Comment by anntzer** [comment] 2017-09-09 18:11
Ah I see.
Well as you say I need both to send the plotly js and the actual plot data.  The first part is done by plotly.offline.init_notebook_mode, so unless that function gets reimplemented (which I'm not going to do) it'll always be in its own message.
In theory I could keep track of whether the notebook has already been init'ed, but note that this may (perhaps?) cause problems if there are multiple frontends at the same time, as they may not get plotly-inited at the same time.  So unless you have a very compelling reason why the current behavior is problematic (from a user-facing point of view) *and* you can convince me this does not affect the multi-frontend case I am not going to change it.

**Comment by anntzer** [comment] 2017-09-26 09:54
@imatlab-helper Let me know what you think about this (no hurry).

**Comment by imatlab-helper** [comment] 2018-01-21 08:32
Apologies on the delay here.

Does this happen every time for every plot, or just for the first time that `imatab_export_fig` is called?

I'll be honest, I don't even know how to pull that view of the duplicate data up. Is that the browser debug window?

**Comment by anntzer** [comment] 2018-03-10 22:26
That's the debug window indeed, you should be able to bring it up with F12 on chrome (for example).

**Comment by anntzer** [comment] 2019-06-12 22:19
Closing for lack of reply to https://github.com/imatlab/imatlab/issues/26#issuecomment-328294371.

**Closed by anntzer** 2019-06-12 22:19 UTC
