### ISSUE TITLE
TypeError for inline figures jpeg and png

### ISSUE THREAD

**Issue by pebbe** [imatlab/imatlab#39] opened 2018-03-10 12:40 UTC
I put this in a notebook cell:
```
imatlab_export_fig('print-jpeg');
```
Then, when I try to plot something, I get this error:
```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/imatlab/_kernel.py", line 206, in do_execute
    self._export_figures()
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/imatlab/_kernel.py", line 251, in _export_figures
    {})
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/imatlab/_kernel.py", line 155, in _send_display_data
    {"data": data, "metadata": metadata or {}})
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 353, in send_response
    ident, buffers, track, header, metadata)
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/jupyter_client/session.py", line 737, in send
    to_send = self.serialize(msg, ident)
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/jupyter_client/session.py", line 625, in serialize
    content = self.pack(content)
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/jupyter_client/session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/net/aps/haytabo/opt/anaconda3/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 93, in date_default
    raise TypeError("%r is not JSON serializable" % obj)

TypeError: b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xfe\x00\x18MATLAB Handle Graphics\xff\xfe\x00\x1dMATLAB,
```
(truncated)

With PNG I get a similar error.

Matlab version: 9.3.0.713579 (R2017b)

**Comment by anntzer** [comment] 2018-03-10 19:51
duplicate of https://github.com/imatlab/imatlab/issues/35? if master fixes the issue for you I'll make a new release.

**Comment by pebbe** [comment] 2018-03-10 20:28
Yes, it works with master.

**Comment by anntzer** [comment] 2018-03-10 23:13
imatlab 0.3 released

**Closed by anntzer** 2018-03-10 23:13 UTC
